[project]
name = "fastapimongodb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.0",
    "jinja2>=3.1.6",
    "pymongo>=4.15.3",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
